app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
# app/config/routing_dev.yml
_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error    
