<?php

namespace AppBundle\Repository;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends \Doctrine\ORM\EntityRepository {

    public function findByQuestions($questions) {
        $query = $this->getEntityManager()
                ->createQuery(
                'SELECT a FROM AppBundle:Answer a WHERE a.question IN (:questions)'
        );

        $query->setParameter('questions', $questions);

        return $query->getResult();
    }

}
