<?php

namespace AppBundle\Repository;

/**
 * BetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BetRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByGames($games) {
        $query = $this->getEntityManager()
                ->createQuery(
                'SELECT b FROM AppBundle:Bet b WHERE b.game IN (:games)'
        );

        $query->setParameter('games', $games);

        return $query->getResult();
    }    
    
}
