<?php

namespace AppBundle\Repository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getFinishedGames() {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT g FROM AppBundle:Game g WHERE g.homeTeamScore IS NOT NULL AND g.guestTeamScore IS NOT NULL'
            )
            ->getResult();       
    }
    
}
