<?php

namespace AppBundle\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository {

    public function getFinishedQuestions() {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT q FROM AppBundle:Question q WHERE q.correctAnswer IS NOT NULL'
                        )
                        ->getResult();
    }

    public function getRankedTeams($type) {
        $query = $this->getEntityManager()->createQuery(
                'SELECT q FROM AppBundle:Question q WHERE q.type = :type'
        );
        
        $query->setParameter('type', $type);
        $result = $query->getResult();

        return $result;
    }

}
